version: '2'
x-extra_hosts:
  &default-extra_hosts
- "master:192.168.2.205"
  # add more host if running on multiple server

services:
  test:
    container_name: test
    image: test
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - PORT=3001
    extra_hosts: *default-extra_hosts
    networks:
      - test
  nginx:
    image: nginx:1.17-alpine
    container_name: nginx
    restart: unless-stopped
    extra_hosts: *default-extra_hosts
    ports:
      - "8001:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - test

networks:
  test:
    driver: bridge
